### ISSUE TITLE
[Version Request] 1.20.1 Forge

### ISSUE THREAD

**Issue by TBlazeWarriorT** [TheCSMods/mc-better-stats#100]
### What is this suggestion for?

Mod Itself

### Suggestion

I just wanted to show some interest in 1.20.1 Forge version of this mod, I hope it doesn't die in 1.19. The mod seems great, and thanks for the attention.

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by TBlazeWarriorT** [comment]
also ay I got exactly issue #100 by accident 🥳

**Comment by TheCSDev** [comment]
Hello!
Thank you for showing interest in the mod, as well as suggesting a port. Also nice, #100!

As for the suggestion, I hate having to say it, but it is unfortunately not in my plans to port the mod.
While I understand that this is disappointing to people who want a Forge port and ports to older versions, I have also provided detailed responses to people asking for ports in the past.

<details>
	<summary>Because I wanna avoid repeating myself, here are some of the resources I wanna link to here (click here)</summary>
	<ul>
		<li>The <a href="https://www.youtube.com/watch?v=AaC8J0G238c&lc=UgwTEyjlCWHp6jis22Z4AaABAg" target="_blank">YouTube comment</a> that was left on my showcase video <img src="https://github.com/TheCSMods/mc-better-stats/assets/66475965/e80c72f8-0b44-475c-855a-1aa85764c6f2" alt="image"></li>
		<li>Issue number #85 (most recent)</li>
	</ul>
</details>

So hopefully that explains everything. If there's anything else you wanna know, feel free to ask. Also, I should probably pin the issue for future reference so people don't accidentally miss it before suggesting again.

Thanks again, as always. Always glad to see people showing interest in the mod. Have a great day as well!

**Comment by TBlazeWarriorT** [comment]
> Hello! Thank you for showing interest in the mod, as well as suggesting a port. Also nice, #100!
> 
> As for the suggestion, I hate having to say it, but it is unfortunately not in my plans to port the mod. While I understand that this is disappointing to people who want a Forge port and ports to older versions, I have also provided detailed responses to people asking for ports in the past.
> 
> Because I wanna avoid repeating myself, here are some of the resources I wanna link to here (click here)
> So hopefully that explains everything. If there's anything else you wanna know, feel free to ask. Also, I should probably pin the issue for future reference so people don't accidentally miss it before suggesting again.
> 
> Thanks again, as always. Always glad to see people showing interest in the mod. Have a great day as well!

Okay, thank you for the fast and detailed respose!

**Comment by TBlazeWarriorT** [comment]
@TheCSDev Oh wow
Holy cow
Seems like your mod actually works out of the box on Forge using Sinytra Connector
Haven't found any errors so far
You might want to keep an eye out on that mod, it might be worth recommending to people who want to use your mod on Forge on the future, super promising
![image](https://github.com/TheCSMods/mc-better-stats/assets/25572454/87412c66-dcdb-45aa-a7f0-2bf5d7782c47)
![image](https://github.com/TheCSMods/mc-better-stats/assets/25572454/088261b9-2deb-4f96-810e-d5158804b5d3)

**Comment by TheCSDev** [comment]
Oh my God, this is the best news I've heard all year!!! Feels like a perfect new year's present.
When I read the GitHub's automated email about your comment, my first reaction to literally scream in excitement and sprint to my computer to try it out, and holy cow it actually works!

Thank you soooo much for bringing this mod to my attention, I shall definitely do whatever I can to tell everyone on Forge to use this mod. This is amazing! I think I could also link that mod from inside of this mod as well, and put it as like a GUI button in the top-bar menu or something.
Also [here's link to the mod so people don't have to search for it](https://www.curseforge.com/projects/890127).

Also happy new year to you as well! This news just made my day 1000 times better.

**Comment by TBlazeWarriorT** [comment]
I had not tested it until now, and to be honest, I didn't expect throwing it on my 120 mod forge modpack to work
But it did and I'm yet to find any error lmao
And it looks even better than I expected
Even the bosses from Cataclysm, a Forge-exclusive mod with highly customized visuals, render properly, I'm goosebumped
![image](https://github.com/TheCSMods/mc-better-stats/assets/25572454/69b80333-b4d9-4175-b61d-15f2be92b3c9)
This is great for us both lol
Happy new year!
