### ISSUE TITLE
[Suggestion] Pin General Stat

### ISSUE THREAD

**Issue by PresleyHudson** [TheCSMods/mc-better-stats#104]
### What is this suggestion for?

Mod Itself

### Suggestion

I would like to pin the fish caught stat but I am unable to

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by TheCSDev** [comment]
That sounds like a good idea.  
I should probably eventually figure this out, as last time I tried it, I ran into some technical issues that eventually made me give up.

Right now the only technical issues I can think of are the fact that custom stats (which is another name for "general stats") can behave in different less-predictible ways, and some custom stats like `minecraft:play_time` literally update once per tick (on the server-side), so getting that counter to update live could result in large performance and network bandwidth costs. However, perhaps a simple rete-limit there for "live stats updates" could do.

Anyway, I'll likely get to it eventually, and when I do, I'll think of something. Right now I'm focusing on what I got going on in v3.8.
Thanks for the suggestion, and have a great day!

**Comment by TheCSDev** [comment]
"It took me two weeks to implement this feature. Don't believe me?... \**opens commit stats*\*"
(that was a joke reference to something random that has to do with... *fish*)

Anyways, as I was working on the next update, I decided to implement this as well, and it is now done. Not sure when the next update will come out however, as there's a bunch more I wanna work on before publishing. I did unfortunately run into the issue of general HUD stats not being able to update in real-time, but hopefully people won't mind waiting a few seconds for them to update.

Have a great day once again!

**Comment by PresleyHudson** [comment]
Awesome! Looking forward to it

**Comment by TheCSDev** [comment]
Update currently published on [GitHub](https://github.com/TheCSMods/mc-better-stats/releases/tag/v3.9).  
Will be publishing on CF and Modrinth soon as well. As such, this issue may be closed now.  
Thank you once again, and have a great day!
