### ISSUE TITLE
 [Suggestion] Add a  way to convert stat formats.

### ISSUE THREAD

**Issue by theendercore** [TheCSMods/mc-better-stats#11]
I would be very cool if you could view your time played in hours or minutes. Or convert km to miles or meters.

**Comment by ajh123** [comment]
It would be nice if this feature supported vanilla Minecraft's JSON - so people can share in that format.

**Comment by TheCSDev** [comment]
I hope almost 2 years wasn't too long of a wait for a response.  

Anyway I finally sort-of implemented this feature, after I got more requests from other people wanting it as well.  
My current implementation needs some more tweaks in my opinion, so I'll do that eventually as well.

Thanks for the suggestion, and have a great day!

**Comment by theendercore** [comment]
yipeeeeee!
I was not expecting this, this has made my day :))))))))))))
