### ISSUE TITLE
[v3.9.2 fabric-1.20.4] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;

### ISSUE THREAD

**Issue by mrdhobbs** [TheCSMods/mc-better-stats#112]
### What happened?

After installing BSS on both my client and server installs of Fabric 1.20.4, I'm getting the following errors every 5 minutes in the server's log:
`[12:46:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
[12:51:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
[12:56:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;`

### Steps to reproduce

1. Downloaded latest version of mod from Modrinth
2. Install on server, then restart the server
3. See the error messages in chat, every 5 minutes

### Relevant log output or crash report

```shell
[12:46:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
[12:51:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
[12:56:48] [tcdcommons:cachedresourcemanager/maid/ERROR]: Failed to clean up cached files;
```

### Other installed mods

1. Minecraft 1.20.4
2. Fabric Loaded 0.15.7
3. Fabric API 0.96.4
4. BetterStats 3.9.2
5. TCDCommons 3.9.2 (also gives the error message without this installed)

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello, and thank you for the bug report.  
Please read https://github.com/TheCSMods/mc-tcdcommons/issues/11 for more info.

**Comment by mrdhobbs** [comment]
Thank you @TheCSDev for the link - I thought I'd searched for any existing bug reports, but obviously not hard enough!
