### ISSUE TITLE
[Suggestion] Port to NeoForge

### ISSUE THREAD

**Issue by NovaViper** [TheCSMods/mc-better-stats#114]
### What is this suggestion for?

Mod Itself

### Suggestion

As the name suggest, it would be nice to have a version of that mod that works on NeoForge. i'm not sure how hard this would be to port over but seeing that NeoForge is a fork of Forge, it shouldn't be too hard to port iirc.

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by TheCSDev** [comment]
Hello, and thank you for taking interest in this mod!  
Unfortunately, I currently do not have plans to maintain any loaders other than FabricMC. More info as to how and why can be found in the [project description on CF and MR](https://modrinth.com/mod/n6PXGAoM#:~:text=What%20about%20Minecraft%20Forge) as well as [Issue #100](https://github.com/TheCSMods/mc-better-stats/issues/100).  
Also, as for the `how hard this would be` part; Given the size of the mod's codebase and its dependency, a port could likely take months to complete as it'd require a rewrite, and possibly even longer for someone like me who doesn't even have much Forge modding experience (one of the reasons I only maintain Fabric).  
Either way, thanks a lot again, for both your suggestion and for taking interest in this mod. I aappreciate it a lot, and hope you have a great day!

**Comment by NovaViper** [comment]
Ah ok! I appreciate the response and you have a good day too!

**Comment by NovaViper** [comment]
Also thank you for making me aware of the Sinytra Connector! I'm going to go and give the mod a try with it

**Comment by TheCSDev** [comment]
That is unfortunately correct. I'll see if I can get something going for 1.21.1 (although likely not). The reason I chose latest version is because that is where I currently am in terms of maintaining the mod. Going back also means backporting and dealing with older codebases and game/Java versions, which usually becomes messy and difficult to deal with.
