### ISSUE TITLE
v3.11[mod_version]+fabric-1.21, When searching in the item search window in Creative Mode, items do not appear.

### ISSUE THREAD

**Issue by ffddf111** [TheCSMods/mc-better-stats#120]
### What happened?

When searching in the item search window in creative mode, no items appear.

### Steps to reproduce

1. You must be in a creative state.
2. Then open your inventory and search for the item.
3. Item results are not coming out.

### Relevant log output or crash report

```shell
doesn't exist
```

### Other installed mods

doesn't exist

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello and thank you for the bug report! Sorry for the delay in my response (likely time-zones..)
I have just checked, and yes, you're right. Interesting behavior on the game's end that I didn't spot, so thanks for informing me! Now apparantly, everything goes back to normal the second you mine your first block in creative mode. This is quite odd indeed. Either way, I'll have a look at what changes were done to the game's item code this time that broke this mod a bit. Probably something to do with the changes they made to the item system and stuff.

Anyway I'm getting myself sidetracked. Thanks again and have a great day! I'll look into this.

**Comment by TheCSDev** [comment]
I have finally found a solution, and will be implementing, testing, and then publishing it. Hopefully it'll all be done soon. Thanks again, a lot for spotting this, and have a great day!

**Comment by ffddf111** [comment]
Have a good day for developers. Thank you for solving
