### ISSUE TITLE
How to remove this button via config

### ISSUE THREAD

**Issue by vico93** [TheCSMods/mc-better-stats#131]
### Question

Is there any way to disable this button that started appearing after i updated the mod and its dependency?

![image](https://github.com/user-attachments/assets/61cea792-6f50-440f-85b9-f08271fef7b6)

**Comment by TheCSDev** [comment]
Hello!  
Another update to this mod will be done soon, and the button will be fully gone. Right now I put it there to spread awareness of that other mod.

I apologize in advance for having this button inconvenience you. There is a way to remove it as well.

To remove it, go to the `config` directory of the Minecraft instance where you encountered this button, and locate a file called `extendedworldselection.json`. That file should contain the config property you are looking for. If you do not see this file, note that it only appears after you close the game instance where you saw that button.

Sorry again for any complications or if I didn't explain it properly. As mentioned, the button will also be completely gone soon as well.

**Comment by vico93** [comment]
Thanks! I just get a little bit startled because it appeared from nowhere and i didnt added any mod that does such thing in my pack (only updated the current ones).

It's certainly an interesting feature, but for me i dont find an use for that yet. But if i require to load a save from outside my profiles directories, i'm sure will give it a try.
