### ISSUE TITLE
[betterstats-2.1.1+1.19.2 forge] Startup crash with mod installed.

### ISSUE THREAD

**Issue by murao-kun** [TheCSMods/mc-better-stats#30]
**Describe the bug**
My instance is crashing on startup. Without crash log. (Probably because it is mixin issue)

**To Reproduce**
Unknown.

**Expected behavior**
To boot game fine.

There are logs:
[debug.log](https://github.com/TheCSMods/mc-better-stats/files/10410155/debug.log)
[latest.log](https://github.com/TheCSMods/mc-better-stats/files/10410157/latest.log)

**Comment by TheCSDev** [comment]
![image](https://user-images.githubusercontent.com/66475965/212291876-67d7f24f-fdee-483a-af9e-8b49b728022a.png)

**Comment by TheCSDev** [comment]
I mean, I even said it in the mod description and the changelogs, in red text...

**Comment by TheCSDev** [comment]
Just in case someone else encounters the same issue, I will explain here as well and then pin this issue. Basically the Forge port of this mod requires [TCDComoons API](https://www.curseforge.com/minecraft/mc-mods/tcdcommons) to be installed as well. While the Fabric version of the mod also uses [TCDComoons API](https://www.curseforge.com/minecraft/mc-mods/tcdcommons), for Fabric it is embedded, so downloading it is not required. I tried doing the same for Forge, but was unsuccessful, hence why you have to download it for Forge.

According to the title of this issue, I see you are using `betterstats v2.1.1+forge-1.19.2`, so you will have to download and install the latest version of [tcdcommons forge-1.19.2](https://www.curseforge.com/minecraft/mc-mods/tcdcommons/files) as well.

Sorry for the confusion if there was any. I see a lot more people are downloadting `betterstats forge-1.19.2` without downloading `tcdcommons` as well, despite it being mentioned as required in the changelogs, so a lot more people are probably running into the same issue as well. This should hopefully help those who encounter the same issue.

**Comment by murao-kun** [comment]
Ohhh, I thought about that and then I checked that it is embed on curseforge download page.
I guess you can setup JiJ (Jar in Jar) thing like create doing with flywheel.
Thank you for explanation!

**Comment by TheCSDev** [comment]
Awesome. Thanks for letting me know about Create doing it. I will definitely have a look at it and see how it does it. Having to download jars separately can be very annoying and can lead to issues like this.
Thanks a lot for letting me know. Have a great day!
