### ISSUE TITLE
[v2.4+fabric-1.19.3] Crash on 1.19.3 with v2.4

### ISSUE THREAD

**Issue by sternschnaube** [TheCSMods/mc-better-stats#41]
![image](https://user-images.githubusercontent.com/120551916/224324421-cf3a1480-ac64-4f09-aeff-99655aa23fc8.png)

**Comment by TheCSDev** [comment]
Hmm, another one of those cases where I miss one line of code, and the entire thing breaks down...
Thanks for reporting it tho! I will quickly have it resolved and published. Have a great day as well.
