### ISSUE TITLE
Add support for 1.19.4 pls

### ISSUE THREAD

**Issue by RinixGG** [TheCSMods/mc-better-stats#43]

**Comment by TheCSDev** [comment]
Yup, working on it.
Right now TCDCommons is screwing me off with one of the most weirdest and most confusing GUI rendering bugs I have ever seen tho. Once I find a way to fix it, I will manage to get this mod to work on 1.19.4.

**Comment by TheCSDev** [comment]
Oh I forgot to close this issue. I finally ported the mod yesterday.
