### ISSUE TITLE
Remove Mouse Tracking

### ISSUE THREAD

**Issue by QueenUlyana** [TheCSMods/mc-better-stats#55]
### What is this suggestion for?

Mod Itself

### Suggestion

**I would like to have a "disable mouse tracking" option. When I'm waving my mouse, the mobs move their heads in its direction, it makes me dizzy. Could you add an option that would disable mouse tracking?**

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by QueenUlyana** [comment]
https://github.com/TheCSMods/mc-better-stats/assets/83131824/64ac8c49-f892-49dd-96af-426b94949db8

**Comment by QueenUlyana** [comment]
**It would also be great to add a frame around the icons of the mobs, for better perception. Preferably customizable, so you can choose the color using RGB.**

**Comment by QueenUlyana** [comment]
Sort of:
![2023-06-09_21 48 13](https://github.com/TheCSMods/mc-better-stats/assets/83131824/8d7067da-6187-4269-8582-9bb86f293b80)

**Comment by TheCSDev** [comment]
Sounds like a good suggestion. Will implement it.
I think I will also have to make it a config option, meaning I will have to finally implement config saving/loading, but stiill, sounds good.

**Comment by TheCSDev** [comment]
Sorry, things got a bit complicated for update v2.9, so I got carried away with it.
Minecraft 1.20 came out before I got to finish v2.9, so I thought I could just publish the unfinished update early and work on porting to 1.20.
Turns out 1.20, like any other update, completely broke all my mods, and It will take a long time to port.
So I decided to work on features I had planned for v2.9 for now, then port to 1.20, and after that possibly implement this.

Due to the nature of 1.20 and how it rewrites a bunch of GUI code of all things, and this mod is a GUI mod that heavily relies on that code, I guess I'll have to stop maintaining all versions before 1.20 once I make the port, as it'd be too much work to handle old and new GUI code at the same time.

**Comment by QueenUlyana** [comment]
> Sorry, things got a bit complicated for update v2.9, so I got carried away with it. Minecraft 1.20 came out before I got to finish v2.9, so I thought I could just publish the unfinished update early and work on porting to 1.20. Turns out 1.20, like any other update, completely broke all my mods, and It will take a long time to port. So I decided to work on features I had planned for v2.9 for now, then port to 1.20, and after that possibly implement this.
> 
> Due to the nature of 1.20 and how it rewrites a bunch of GUI code of all things, and this mod is a GUI mod that heavily relies on that code, I guess I'll have to stop maintaining all versions before 1.20 once I make the port, as it'd be too much work to handle old and new GUI code at the same time.

Understandable, but I'll still be waiting for the update for version 1.19.4. I won't play version 1.20, I didn't like it very much

**Comment by TheCSDev** [comment]
Heya!
I added a config feature to disable GUI mob rotation alongside my update v2.9.1.
However, I didn't add the stat outline one tho, as I'm very tight on time, and I'm also "behind" on the 1.20 port (haven't even started it yet).

Also also, altho the config feature will work on mob stats, I tried applying it to the player element, and it kinda looked weird (a bug I had no time to fix), so the player element that you'll encounter in the general stats (v2.9.1) will remain unaffected:

![Screenshot 2023-06-14 181100](https://github.com/TheCSMods/mc-better-stats/assets/66475965/ea98c24e-da9a-41c1-a129-a7347ee7f885)

**Comment by QueenUlyana** [comment]
> 

Thanks, I'll check it out when I get home. Only it seems to me that mobs look at different angles. The angle mobs of rotation is too big. I also noticed that the zombie on the right is too small.

**Comment by TheCSDev** [comment]
Ah, the tiny zombie.. Yes, that's a Giant I believe.
So what this mod does is it "scales" the mobs up or down to fit the square boxes based on their model sizes, and then tells Minecraft to render them. However, some mobs have weird hitboxes and model sizes, which can cause them to look weird in terms of size.

Fun fact:
Initially the Ender Dragon model size is so weirdly wide (which makes sense) that it made the Dragon not render at all, so I had to scale the render by x4 (four times) to make it visible. I could do the same for Giant, but likely any future patch will be in `1.20+` as I'm currently working on the port.

## -

As for some mobs looking in weird angles, that has basically nothing to do with this mod. As mentioned earler, this mod tells Minecraft (Mojang's code) to render the mobs on the screen, so in other words, it's an issue on their end. So, I guess the only option to fix that would be to send bug reports over to Mojang
(but they usually don't wanna listen when they see you have a modded environment running, even tho using a modded environment is the only way to spot those bugs in the first place).

## -

So in a way, I technically *can* make hard-coded adjustments for each mob individually, but that's like super inefficient. It costs a bunch of extra performance, it doesn't account for the fact that a mob can be added and modified at any point in time, and practically speaking, there's infinitely many mobs that can be added to the game. This mod would somehow have to account for all of that, which is straight-up impossible.

## -

Anyways, hopefully that feature was at least somewhat helpful, and have a great day as well!
