### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by ItzSkyReed** [TheCSMods/mc-better-stats#56]
### Question

Please update your mod, it is very useful

**Comment by TheCSDev** [comment]
Hello. Please see the last comment I made on #55.
I'll work on it soon. Thanks for the suggestion tho.

**Comment by ItzSkyReed** [comment]
Ok. Thanks

**Comment by TheCSDev** [comment]
By the way, I managed to publish an alpha version yesterday in case you didn't see it:
https://www.curseforge.com/minecraft/mc-mods/better-stats/files/4590283
