### ISSUE TITLE
[v2.9+any] Player model doesnt fit the player profile panel

### ISSUE THREAD

**Issue by Rozbiynk** [TheCSMods/mc-better-stats#58]
### What happened?

![изображение](https://github.com/TheCSMods/mc-better-stats/assets/66475965/c5340114-2615-421d-952c-8be7a6da0a46)
(edit from TheCSDev: sorry, i felt it would be more appropriate to keep potentionally personal info censored)

### Steps to reproduce

Open mod

### Relevant log output or crash report

```shell
Edit by TheCSDev: Removed the logs link as it contained potentially sensitive information that could compromise privacy.
```

### Other installed mods

Edit by TheCSDev: I took down the mod list link because of a major security issue.

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello!
Thanks for reporting the bug. After a quick test, I came to the conclusion that another "rendering"-related mod is messing with the player model, as it looks fine without other mods installed.
Also your mod list is massive, likely a mod-pack? Would be easier to debug if I could install all of them at once via a mod-pack.

Anyways yeah, sorry about that, this is similar to what happened with #57. A bunch of other mods like to mess with how the player is rendered on the screen, causing weird issues like that. Best I can do is try and counter it in the next update by scaling down.
