### ISSUE TITLE
Seed display issues

### ISSUE THREAD

**Issue by HuangKOOO** [TheCSMods/mc-better-stats#68]
### Question

Entering a command to get a different seed than the one shown in the module's interface

**Comment by TheCSDev** [comment]
Hello.  
Were you trying to ask why the world seed shown on the Better Statistics Screen is different from the one shown by `/seed`?  
If so, then the answer is simple: That's not the actual world seed, it's the SHA256 hash of the real seed, aka the "biome access" seed.

Here's how it works:
- Basically the server hashes the real world seed with the SHA256 hashing algorithm, which produces a variable called "biome access", and this variable is then sent over to the client for biome noise stuff (whatever that is, becuase I don't 100% know either).
- This "biome access" variable is then shown in the Better Statistics Screen menu when debug mode is turned on.
- As for knowing the real seed, that's impossible unless you have [permission level 2](https://minecraft.fandom.com/wiki/Permission_level#Java_Edition) and can execute `/seed` yourself.

More info here as well:
- [Minecraft Protocol](https://wiki.vg/Protocol#Login_.28play.29) at `0x28 | Play Client | Hashed seed | Long | First 8 bytes of the SHA-256 hash of the world's seed. Used client side for biome noise`
