### ISSUE TITLE
BSS 3.1 for 1.20.2 not on Modrinth

### ISSUE THREAD

**Issue by MeeniMc** [TheCSMods/mc-better-stats#77]
### Question

BSS 3.1 for 1.20.2 is available here and on CF, but it is not on Modrinth. The latest version that got uploaded there is for 1.20.1 only.

**Comment by TheCSDev** [comment]
Oh my apologies, forgot to publish.
Will do now.

**Comment by TheCSDev** [comment]
All done. Thanks for reminding me. Have a great day!
