### ISSUE TITLE
[v3.2+fabric-1.20.1] View stats other player dont work

### ISSUE THREAD

**Issue by mindryder** [TheCSMods/mc-better-stats#81]
### What happened?

In versions 2.10 all works fine, if press server connect button, seen new button search where write name other player name and view his stats, now in versions 3, after press nothing change, cant view other players stats & etc.

### Steps to reproduce

1. Go to...
2. Then do...
3. See the bug or issue or a crash

### Other installed mods

own modpack

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello, and thanks for your report.
I think you may be referring to the fact that the feature to view other player's stats by requesting them from the server is completely gone. There is however, a new feature where you can export your stats to a file and share and open those files instead.

For more info and the reason it was done, [please read the v3.0 changelog](https://legacy.curseforge.com/minecraft/mc-mods/better-stats/files/4777062).

Have a great day!
